services:
  web:
    container_name: sinatra-cnt02
    image: sinatra-app-img-02
    build: .
    command: bundle exec ruby app.rb
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: ./app
        target: /app
    tty: true

